-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "name" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "Audit" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "advisorName" TEXT NOT NULL,
    "firmName" TEXT NOT NULL,
    "email" TEXT,
    "phone" TEXT,
    "currentFirm" TEXT,
    "currentCustodian" TEXT,
    "futureCustodian" TEXT,
    "businessModel" TEXT NOT NULL,
    "protocolStatus" TEXT NOT NULL,
    "totalAum" REAL,
    "annualRevenue" REAL,
    "households" INTEGER,
    "accounts" INTEGER,
    "staffCount" INTEGER,
    "crm" TEXT,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "emailCompletenessPercent" REAL NOT NULL DEFAULT 0,
    "phoneCompletenessPercent" REAL NOT NULL DEFAULT 0,
    "addressCompletenessPercent" REAL NOT NULL DEFAULT 0,
    "householdingQualityScore" INTEGER NOT NULL DEFAULT 1,
    "duplicateRecordRiskScore" INTEGER NOT NULL DEFAULT 1,
    "clientNotesQualityScore" INTEGER NOT NULL DEFAULT 1,
    "kycUpdateFrequency" TEXT NOT NULL DEFAULT 'Ad-hoc',
    "trustedContactCompletenessPercent" REAL NOT NULL DEFAULT 0,
    "beneficiaryReviewStatus" TEXT NOT NULL DEFAULT 'None',
    "riskToleranceCurrentPercent" REAL NOT NULL DEFAULT 0,
    "investmentObjectiveCurrentPercent" REAL NOT NULL DEFAULT 0,
    "missingSignatureRiskScore" INTEGER NOT NULL DEFAULT 1,
    "documentStorageQualityScore" INTEGER NOT NULL DEFAULT 1,
    "percentIraAccounts" REAL NOT NULL DEFAULT 0,
    "percentTrustAccounts" REAL NOT NULL DEFAULT 0,
    "percentEntityAccounts" REAL NOT NULL DEFAULT 0,
    "percentAnnuityAltAccounts" REAL NOT NULL DEFAULT 0,
    "directBusinessAmount" REAL NOT NULL DEFAULT 0,
    "heldAwayAssetsNotes" TEXT,
    "transferComplexityScore" INTEGER NOT NULL DEFAULT 1,
    "staffCapacityScore" INTEGER NOT NULL DEFAULT 1,
    "crmExportQualityScore" INTEGER NOT NULL DEFAULT 1,
    "taskManagementScore" INTEGER NOT NULL DEFAULT 1,
    "digitalSignatureReadinessScore" INTEGER NOT NULL DEFAULT 1,
    "communicationPlanScore" INTEGER NOT NULL DEFAULT 1,
    "employmentAgreementReviewed" BOOLEAN NOT NULL DEFAULT false,
    "nonSolicitNonCompeteConcerns" BOOLEAN NOT NULL DEFAULT false,
    "legalReviewStatus" TEXT NOT NULL DEFAULT 'None',
    "complianceRiskNotes" TEXT,
    "overallReadinessScore" REAL NOT NULL DEFAULT 0,
    "clientDataScore" REAL NOT NULL DEFAULT 0,
    "kycDocumentationScore" REAL NOT NULL DEFAULT 0,
    "transferComplexityScoreVal" REAL NOT NULL DEFAULT 0,
    "operationalScore" REAL NOT NULL DEFAULT 0,
    "complianceProtocolScore" REAL NOT NULL DEFAULT 0,
    "communicationScore" REAL NOT NULL DEFAULT 0,
    "createdByUserId" TEXT,
    CONSTRAINT "Audit_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
